# Generated by Django 4.2.2 on 2023-07-05 17:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FarmCopy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "county",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ]
                    ),
                ),
                (
                    "parish",
                    models.CharField(
                        max_length=3,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.MaxLengthValidator(3),
                        ],
                    ),
                ),
                (
                    "holding_number",
                    models.CharField(
                        max_length=5,
                        validators=[
                            django.core.validators.MinLengthValidator(5),
                            django.core.validators.MaxLengthValidator(5),
                        ],
                    ),
                ),
                ("address_line1", models.CharField(max_length=100)),
                ("address_line2", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("postcode", models.CharField(max_length=10)),
                ("farm_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="OwnerCopy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="IncidentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident_number",
                    models.CharField(
                        max_length=8,
                        validators=[
                            django.core.validators.MinLengthValidator(8),
                            django.core.validators.MaxLengthValidator(8),
                        ],
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("S", "Suspected"),
                            ("C", "Confirmed"),
                            ("E", "Ended"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="reports.farmcopy",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="farmcopy",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="reports.ownercopy"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="farmcopy",
            unique_together={("county", "parish", "holding_number")},
        ),
    ]
