# Generated by Django 4.2.2 on 2023-07-14 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incidentreport",
            name="incident_number",
            field=models.CharField(
                max_length=8,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(8),
                    django.core.validators.MaxLengthValidator(8),
                ],
            ),
        ),
    ]
