# Generated by Django 4.2.2 on 2023-07-17 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_alter_incidentreport_incident_number"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="farmcopy",
            unique_together=set(),
        ),
    ]
