# Generated by Django 4.2.2 on 2023-07-24 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reports", "0004_alter_farmcopy_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidentreport",
            name="assigned_to",
            field=models.ForeignKey(
                default=reports.models.get_admin_user_id,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="assigned_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
